# PANDAS
 - PANDAS IS A FAST ,POWERFUL AND EASY TO USE OPEN SOURCE DATA ANALYSIS AND MANUPULATION LIBRARY
   
  - DATA FRAME
  - SERIES


# What is Pandas?
Pandas is a Python library used for data manipulation and analysis. It helps us load, clean, transform, filter, and analyze structured data such as CSV files, Excel files, and SQL tables. It provides powerful data structures like Series and DataFrame and is built on top of NumPy."

Why do we use Pandas?

We use Pandas to::

Read data from CSV, Excel, SQL, JSON, etc.
Clean missing or duplicate data..
Filter and sort data.
Perform calculations.
Group and summarize data.
Merge and join datasets

In [1]:
import numpy as np
import pandas as pd

## SERIES

In [129]:
data=[10,20,30,40,50]
s1 = pd.Series(data)
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [130]:
type(s1)

pandas.core.series.Series

In [131]:
s1.values

array([10, 20, 30, 40, 50])

In [132]:
s1.index

RangeIndex(start=0, stop=5, step=1)

In [133]:
list(s1.index)

[0, 1, 2, 3, 4]

In [134]:
data=[11,22,33,44,55]
s1 = pd.Series(data)
s1.index = [101,102,103,104,105]     # define index
s1

101    11
102    22
103    33
104    44
105    55
dtype: int64

In [229]:
data=[11,22,33,44,55]
s1 = pd.Series(data)
s1.index = ['A','B','C','D','E']     # define index
s1

A    11
B    22
C    33
D    44
E    55
dtype: int64

In [233]:
s1.index = range(1005,1010)     # define index
s1

1005    11
1006    22
1007    33
1008    44
1009    55
dtype: int64

## ACCESSING DATA IN SERIES

In [228]:
s1[0]

KeyError: 0

In [230]:
s1['A']

np.int64(11)

In [231]:
s1.iloc[1]           # default index iloc

np.int64(22)

In [238]:
s1.loc[1005]       # define index loc

np.int64(11)

# ADD UPDATE AND DELETETE OPERATIONS

In [ ]:
s1['F'] = 60
s1

In [ ]:
s1['B'] = 75

In [ ]:
s1

In [ ]:
s1.drop('E')

In [ ]:
s1

In [ ]:
s2 = s1.drop('E')
s2

# if we want to chage s1 permently then

In [ ]:
s1.drop('E',inplace = True)
s1

In [ ]:
s1

# slicing

In [ ]:
s1[:]

In [ ]:
s1[2:4]

In [ ]:
s1[::-1]

## CREATING SERIRES DATA FROM A DICTIONARAY

In [240]:
data = {'jaipur':'Rajasthan',
        'Mumbai'        :'Maharashtra',
         'Kolkata':' West Bengal',
         'Chandigarh':'Punjab',
         'patna'      : 'Bihar' ,
         'Lucknow' : 'Uttar pradesh'
          }

In [241]:
s2 = pd.Series(data)
s2

jaipur            Rajasthan
Mumbai          Maharashtra
Kolkata         West Bengal
Chandigarh           Punjab
patna                 Bihar
Lucknow       Uttar pradesh
dtype: object

In [242]:
s2.iloc[1]

'Maharashtra'

In [243]:
s2.loc['Mumbai']

'Maharashtra'

In [244]:
s2.index

Index(['jaipur', 'Mumbai', 'Kolkata', 'Chandigarh', 'patna', 'Lucknow'], dtype='object')

In [245]:
s2.values

array(['Rajasthan', 'Maharashtra', ' West Bengal', 'Punjab', 'Bihar',
       'Uttar pradesh'], dtype=object)

In [246]:
s2.name = 'States and Capitals'
s2

jaipur            Rajasthan
Mumbai          Maharashtra
Kolkata         West Bengal
Chandigarh           Punjab
patna                 Bihar
Lucknow       Uttar pradesh
Name: States and Capitals, dtype: object

In [247]:
s2.index.name = 'Capitals'
s2

Capitals
jaipur            Rajasthan
Mumbai          Maharashtra
Kolkata         West Bengal
Chandigarh           Punjab
patna                 Bihar
Lucknow       Uttar pradesh
Name: States and Capitals, dtype: object

In [248]:
s2[0:3:2]

Capitals
jaipur        Rajasthan
Kolkata     West Bengal
Name: States and Capitals, dtype: object

In [249]:
s2.loc[['jaipur','Kolkata']]   # check this ....

Capitals
jaipur        Rajasthan
Kolkata     West Bengal
Name: States and Capitals, dtype: object

In [ ]:
s2

In [250]:
s3 = pd.Series(data =s2, index=['jaipur','Mumbai','Delhi','Bangaluru','Lucknow'])
s3

jaipur           Rajasthan
Mumbai         Maharashtra
Delhi                  NaN
Bangaluru              NaN
Lucknow      Uttar pradesh
Name: States and Capitals, dtype: object

# FUNCTIONS

In [251]:
s3.isnull()

jaipur       False
Mumbai       False
Delhi         True
Bangaluru     True
Lucknow      False
Name: States and Capitals, dtype: bool

In [252]:
s3.isnull().sum()

np.int64(2)

In [253]:
s3.notnull()

jaipur        True
Mumbai        True
Delhi        False
Bangaluru    False
Lucknow       True
Name: States and Capitals, dtype: bool

In [254]:
s3.notnull().sum()

np.int64(3)

In [262]:
s3['Chandigarh'] = 'Punjab'
s3['Kolkata']    = 'West Bengal'
s3 ['Gandhi Nagar'] = 'Gujrat'
s3

jaipur              Rajasthan
Mumbai            Maharashtra
Delhi                     NaN
Bangaluru                 NaN
Lucknow         Uttar pradesh
abc                    Punjab
Chandigarh             Punjab
Kolkata           West Bengal
Gandhi Nagar           Gujrat
Name: States and Capitals, dtype: object

In [263]:
s3.head()

jaipur           Rajasthan
Mumbai         Maharashtra
Delhi                  NaN
Bangaluru              NaN
Lucknow      Uttar pradesh
Name: States and Capitals, dtype: object

In [256]:
s3.head(3)

jaipur      Rajasthan
Mumbai    Maharashtra
Delhi             NaN
Name: States and Capitals, dtype: object

In [257]:
s3.tail()

jaipur           Rajasthan
Mumbai         Maharashtra
Delhi                  NaN
Bangaluru              NaN
Lucknow      Uttar pradesh
Name: States and Capitals, dtype: object

In [258]:
s3.tail(6)

jaipur           Rajasthan
Mumbai         Maharashtra
Delhi                  NaN
Bangaluru              NaN
Lucknow      Uttar pradesh
Name: States and Capitals, dtype: object

In [259]:
s3['abc'] ='Punjab'
s3

jaipur           Rajasthan
Mumbai         Maharashtra
Delhi                  NaN
Bangaluru              NaN
Lucknow      Uttar pradesh
abc                 Punjab
Name: States and Capitals, dtype: object

In [264]:
s3.duplicated()

jaipur          False
Mumbai          False
Delhi           False
Bangaluru        True
Lucknow         False
abc             False
Chandigarh       True
Kolkata         False
Gandhi Nagar    False
Name: States and Capitals, dtype: bool

In [265]:
s3.duplicated().sum()

np.int64(2)

In [266]:
s3.drop_duplicates(inplace=True)

In [267]:
s3

jaipur              Rajasthan
Mumbai            Maharashtra
Delhi                     NaN
Lucknow         Uttar pradesh
abc                    Punjab
Kolkata           West Bengal
Gandhi Nagar           Gujrat
Name: States and Capitals, dtype: object

In [268]:
s3

jaipur              Rajasthan
Mumbai            Maharashtra
Delhi                     NaN
Lucknow         Uttar pradesh
abc                    Punjab
Kolkata           West Bengal
Gandhi Nagar           Gujrat
Name: States and Capitals, dtype: object

## DATA FRAMES

In [2]:
employee1 = pd.Series({'NAME' :'ANKUR','GENDER':'MALE','SALARY':10000})
employee2 = pd.Series({'NAME' :'SARWAT','GENDER':'FEMALE','SALARY':12890000})
employee3 = pd.Series({'NAME' :'GEETANJALI','GENDER':'FEMALE','SALARY':15670000})
employee4 = pd.Series({'NAME' :'DISHA','GENDER':'FEMALE','SALARY':4500000})
employee5 = pd.Series({'NAME' :'ARCHIT','GENDER':'MALE','SALARY':12500000})
employee6 = pd.Series({'NAME' :'ANIKET','GENDER':'MALE','SALARY':2340000})
employee7 = pd.Series({'NAME' :'TEJASHRI','GENDER':'FEMALE','SALARY':76590000})
employee8 = pd.Series({'NAME' :'ATHARVA','GENDER':'MALE','SALARY':34520000})
employee9 = pd.Series({'NAME' :'VARAD','GENDER':'MALE','SALARY':1007800})
employee10 = pd.Series({'NAME' :'NISHA','GENDER':'FEMALE','SALARY':45630000})
employee11 = pd.Series({'NAME' :'ATHARY','GENDER':'MALE','SALARY':78650000})
employee12 = pd.Series({'NAME' :'SAHIL','GENDER':'MALE','SALARY':56740000})
employee13 = pd.Series({'NAME' :'UTKARSHA','GENDER':'MALE','SALARY':567410000})
employee14 = pd.Series({'NAME' :'MIRAL','GENDER':'FEMALE','SALARY':456310000})
employee15 = pd.Series({'NAME' :'VAISHNAVI','GENDER':'FEMALE','SALARY':786540000})

In [3]:
employee = [employee1,employee2,employee3,employee4,employee5,employee6,employee7,employee8,employee9,employee10,employee11,employee12,employee13,employee14,employee15]
df = pd.DataFrame(data=employee,index=range(101,116))
df

           NAME  GENDER     SALARY
101       ANKUR    MALE      10000
102      SARWAT  FEMALE   12890000
103  GEETANJALI  FEMALE   15670000
104       DISHA  FEMALE    4500000
105      ARCHIT    MALE   12500000
106      ANIKET    MALE    2340000
107    TEJASHRI  FEMALE   76590000
108     ATHARVA    MALE   34520000
109       VARAD    MALE    1007800
110       NISHA  FEMALE   45630000
111      ATHARY    MALE   78650000
112       SAHIL    MALE   56740000
113    UTKARSHA    MALE  567410000
114       MIRAL  FEMALE  456310000
115   VAISHNAVI  FEMALE  786540000

# IMPORTING CSV FILE

In [ ]:
df1 = pd.read_csv('drug200.csv')          # file name

In [ ]:
df.info()

In [ ]:
df.head()     # it will return top 5 value

In [ ]:
df.tail()

In [ ]:
df.head(8)

In [ ]:
df.tail(2)

In [ ]:
df.name = 'Employee Details'
df.index.name= 'Employee_Id'

In [ ]:


df.index.name

In [ ]:
df.columns

## ACESSING DATA FROM DATA FRAME

In [ ]:
df

In [ ]:
df['NAME']         # output in series bcx it is single dimention

In [ ]:
df[['NAME']]        # output in data frame formant bcx it is two dimention

In [ ]:
df[['NAME' ,"SALARY"]]

In [ ]:
col = ['NAME','SALARY']
df[col]

In [ ]:
df.loc[111]       # it will return in series bcz []

In [ ]:
df.loc[[111]]         # it will return in data FRAME format [[]]

In [ ]:
# for multi value access from data set 
df.loc[[101,102,103,104,105]]

## ACCESING THE SPECIFIC VALUE 

df.loc[[101],['NAME']]

In [ ]:
df.loc[[101],['NAME']]

In [ ]:
df.loc[[108],['NAME']]

In [ ]:
 df['NAME'][108]

In [ ]:
df.loc[108,'NAME']

In [ ]:
df.loc[[101,102,103,104],['NAME']]

In [ ]:
df.loc[102:115:2]

## ADDING AND DELTED ROW AND COLUMNS

In [82]:
df

           NAME  GENDER     SALARY
101       ANKUR    MALE      10000
102      SARWAT  FEMALE   12890000
103  GEETANJALI  FEMALE   15670000
104       DISHA  FEMALE    4500000
105      ARCHIT    MALE   12500000
106      ANIKET    MALE    2340000
107    TEJASHRI  FEMALE   76590000
108     ATHARVA    MALE   34520000
109       VARAD    MALE    1007800
110       NISHA  FEMALE   45630000
111      ATHARY    MALE   78650000
112       SAHIL    MALE   56740000
113    UTKARSHA    MALE  567410000
114       MIRAL  FEMALE  456310000
115   VAISHNAVI  FEMALE  786540000

In [151]:
df.loc[116] = ['ETHANS','MALE',100,25]
df

                   NAME  GENDER     SALARY  AGE
Employee_Id
101               ANKUR    MALE      10000   32
102              SARWAT  FEMALE   12890000   49
103          GEETANJALI  FEMALE   15670000   29
104               DISHA  FEMALE    4500000   47
105              ARCHIT    MALE   12500000   29
106              ANIKET    MALE    2340000   30
107            TEJASHRI  FEMALE   76590000   38
108             ATHARVA    MALE   34520000   38
109               VARAD    MALE    1007800   26
110               NISHA  FEMALE   45630000   27
111              ATHARY    MALE   78650000   53
112               SAHIL    MALE   56740000   49
113            UTKARSHA    MALE  567410000   53
114               MIRAL  FEMALE  456310000   52
115           VAISHNAVI  FEMALE  786540000   42
116              ETHANS    MALE        100   25

In [154]:
df['NOTICE_DAY'] = 20
df

                   NAME  GENDER     SALARY  AGE  NOTICE_DAY
Employee_Id
101               ANKUR    MALE      10000   32          20
102              SARWAT  FEMALE   12890000   49          20
103          GEETANJALI  FEMALE   15670000   29          20
104               DISHA  FEMALE    4500000   47          20
105              ARCHIT    MALE   12500000   29          20
106              ANIKET    MALE    2340000   30          20
107            TEJASHRI  FEMALE   76590000   38          20
108             ATHARVA    MALE   34520000   38          20
109               VARAD    MALE    1007800   26          20
110               NISHA  FEMALE   45630000   27          20
111              ATHARY    MALE   78650000   53          20
112               SAHIL    MALE   56740000   49          20
113            UTKARSHA    MALE  567410000   53          20
114               MIRAL  FEMALE  456310000   52          20
115           VAISHNAVI  FEMALE  786540000   42          20
116              ETHANS    MALE        100   25          20

In [155]:
df['NOTICE_DAY'] = np.random.randint(1,50,16)
df

                   NAME  GENDER     SALARY  AGE  NOTICE_DAY
Employee_Id
101               ANKUR    MALE      10000   32          32
102              SARWAT  FEMALE   12890000   49          37
103          GEETANJALI  FEMALE   15670000   29           5
104               DISHA  FEMALE    4500000   47           4
105              ARCHIT    MALE   12500000   29          39
106              ANIKET    MALE    2340000   30          39
107            TEJASHRI  FEMALE   76590000   38           6
108             ATHARVA    MALE   34520000   38          27
109               VARAD    MALE    1007800   26          18
110               NISHA  FEMALE   45630000   27           6
111              ATHARY    MALE   78650000   53          11
112               SAHIL    MALE   56740000   49          27
113            UTKARSHA    MALE  567410000   53           2
114               MIRAL  FEMALE  456310000   52           3
115           VAISHNAVI  FEMALE  786540000   42          20
116              ETHANS    MALE        100   25          46

In [156]:
df['CITY'] = 'PUNE'
df

                   NAME  GENDER     SALARY  AGE  NOTICE_DAY  CITY
Employee_Id
101               ANKUR    MALE      10000   32          32  PUNE
102              SARWAT  FEMALE   12890000   49          37  PUNE
103          GEETANJALI  FEMALE   15670000   29           5  PUNE
104               DISHA  FEMALE    4500000   47           4  PUNE
105              ARCHIT    MALE   12500000   29          39  PUNE
106              ANIKET    MALE    2340000   30          39  PUNE
107            TEJASHRI  FEMALE   76590000   38           6  PUNE
108             ATHARVA    MALE   34520000   38          27  PUNE
109               VARAD    MALE    1007800   26          18  PUNE
110               NISHA  FEMALE   45630000   27           6  PUNE
111              ATHARY    MALE   78650000   53          11  PUNE
112               SAHIL    MALE   56740000   49          27  PUNE
113            UTKARSHA    MALE  567410000   53           2  PUNE
114               MIRAL  FEMALE  456310000   52           3  PUNE
115           VAISHNAVI  FEMALE  786540000   42          20  PUNE
116              ETHANS    MALE        100   25          46  PUNE

# DELTEING THE COL

In [165]:
df.drop('NOTICE_DAY', axis=1,inplace=True)
df

                   NAME  GENDER     SALARY  AGE
Employee_Id
101               ANKUR    MALE      10000   32
102              SARWAT  FEMALE   12890000   49
103          GEETANJALI  FEMALE   15670000   29
104               DISHA  FEMALE    4500000   47
105              ARCHIT    MALE   12500000   29
106              ANIKET    MALE    2340000   30
107            TEJASHRI  FEMALE   76590000   38
108             ATHARVA    MALE   34520000   38
109               VARAD    MALE    1007800   26
110               NISHA  FEMALE   45630000   27
111              ATHARY    MALE   78650000   53
112               SAHIL    MALE   56740000   49
113            UTKARSHA    MALE  567410000   53
114               MIRAL  FEMALE  456310000   52
115           VAISHNAVI  FEMALE  786540000   42
116              ETHANS    MALE        100   25

In [168]:
# deleting the row

df.drop(115, axis=0,inplace=True)
df

                   NAME  GENDER     SALARY  AGE
Employee_Id
101               ANKUR    MALE      10000   32
102              SARWAT  FEMALE   12890000   49
103          GEETANJALI  FEMALE   15670000   29
104               DISHA  FEMALE    4500000   47
105              ARCHIT    MALE   12500000   29
106              ANIKET    MALE    2340000   30
107            TEJASHRI  FEMALE   76590000   38
108             ATHARVA    MALE   34520000   38
109               VARAD    MALE    1007800   26
110               NISHA  FEMALE   45630000   27
111              ATHARY    MALE   78650000   53
112               SAHIL    MALE   56740000   49
113            UTKARSHA    MALE  567410000   53
114               MIRAL  FEMALE  456310000   52

In [313]:
df

                   NAME  GENDER     SALARY AGE       CITY
Employee_Id
101               ANKUR    MALE      10000  32     Mumbai
102              SARWAT  FEMALE   12890000  49     Mumbai
103          GEETANJALI  FEMALE   15670000  29  Hyderabad
104               DISHA  FEMALE    4500000  47    Kolkata
105              ARCHIT    MALE   12500000  29  Ahmedabad
106              ANIKET    MALE    2340000  30  Hyderabad
107            TEJASHRI  FEMALE   76590000  38  Ahmedabad
108             ATHARVA    MALE   34520000  38  Ahmedabad
109             SHUBHAM    MALE    5500000  24     Mumbai
110               NISHA  FEMALE   45630000  27  Bengaluru
111              ATHARY    MALE   78650000  53  Hyderabad
112               SAHIL    MALE   56740000  49      Delhi
113            UTKARSHA    MALE  567410000  53  Bengaluru
114               MIRAL  FEMALE  456310000  52     Mumbai
115               rakhi  female     555555  24    Chennai

In [315]:
NAME = input('enter a name :')
GENDER= input('enter gender :')
SALARY = int(input("Enter salary"))
AGE = int(input("AGE")) 
CITY = input("enter city")
df.loc[116] = [NAME,GENDER,SALARY,AGE,CITY]
df

enter a name : ZZZZ
enter gender : MALE
Enter salary 1254693
AGE 25
enter city pUNE

                   NAME  GENDER     SALARY AGE       CITY
Employee_Id
101               ANKUR    MALE      10000  32     Mumbai
102              SARWAT  FEMALE   12890000  49     Mumbai
103          GEETANJALI  FEMALE   15670000  29  Hyderabad
104               DISHA  FEMALE    4500000  47    Kolkata
105              ARCHIT    MALE   12500000  29  Ahmedabad
106              ANIKET    MALE    2340000  30  Hyderabad
107            TEJASHRI  FEMALE   76590000  38  Ahmedabad
108             ATHARVA    MALE   34520000  38  Ahmedabad
109             SHUBHAM    MALE    5500000  24     Mumbai
110               NISHA  FEMALE   45630000  27  Bengaluru
111              ATHARY    MALE   78650000  53  Hyderabad
112               SAHIL    MALE   56740000  49      Delhi
113            UTKARSHA    MALE  567410000  53  Bengaluru
114               MIRAL  FEMALE  456310000  52     Mumbai
115               rakhi  female     555555  24    Chennai
116                ZZZZ    MALE    1254693  25       pUNE

 # UPDATE THE PARTICULAR VALUE

In [173]:
df.loc[115,'SALARY']  = 555555
df

                   NAME  GENDER     SALARY  AGE
Employee_Id
101               ANKUR    MALE      10000   32
102              SARWAT  FEMALE   12890000   49
103          GEETANJALI  FEMALE   15670000   29
104               DISHA  FEMALE    4500000   47
105              ARCHIT    MALE   12500000   29
106              ANIKET    MALE    2340000   30
107            TEJASHRI  FEMALE   76590000   38
108             ATHARVA    MALE   34520000   38
109               VARAD    MALE    1007800   26
110               NISHA  FEMALE   45630000   27
111              ATHARY    MALE   78650000   53
112               SAHIL    MALE   56740000   49
113            UTKARSHA    MALE  567410000   53
114               MIRAL  FEMALE  456310000   52
115               rakhi  female     555555   24
116                 NaN     NaN     555555  NaN

## ACCESSING DATA BASED ON CONDITION

In [4]:
df

           NAME  GENDER     SALARY
101       ANKUR    MALE      10000
102      SARWAT  FEMALE   12890000
103  GEETANJALI  FEMALE   15670000
104       DISHA  FEMALE    4500000
105      ARCHIT    MALE   12500000
106      ANIKET    MALE    2340000
107    TEJASHRI  FEMALE   76590000
108     ATHARVA    MALE   34520000
109       VARAD    MALE    1007800
110       NISHA  FEMALE   45630000
111      ATHARY    MALE   78650000
112       SAHIL    MALE   56740000
113    UTKARSHA    MALE  567410000
114       MIRAL  FEMALE  456310000
115   VAISHNAVI  FEMALE  786540000

In [319]:
df[df.AGE > 40]

                 NAME  GENDER     SALARY AGE       CITY
Employee_Id
102            SARWAT  FEMALE   12890000  49     Mumbai
104             DISHA  FEMALE    4500000  47    Kolkata
111            ATHARY    MALE   78650000  53  Hyderabad
112             SAHIL    MALE   56740000  49      Delhi
113          UTKARSHA    MALE  567410000  53  Bengaluru
114             MIRAL  FEMALE  456310000  52     Mumbai

In [333]:
df.loc[(df.AGE > 40) &( df.GENDER == 'MALE'),['CITY','NAME']]

                  CITY      NAME
Employee_Id
111          Hyderabad    ATHARY
112              Delhi     SAHIL
113          Bengaluru  UTKARSHA

In [331]:
df[df.AGE > 40][['NAME']]

                 NAME
Employee_Id
102            SARWAT
104             DISHA
111            ATHARY
112             SAHIL
113          UTKARSHA
114             MIRAL

In [184]:
df[df.NAME=='ANKUR']

              NAME GENDER SALARY AGE
Employee_Id
101          ANKUR   MALE  10000  32

In [185]:
df[df.NAME=='ANKUR'][['AGE']]

            AGE
Employee_Id
101          32

In [186]:
df[df.NAME=='ANKUrrR'][['AGE']]

Empty DataFrame
Columns: [AGE]
Index: []

In [188]:
df[df.GENDER=='MALE']

                 NAME GENDER     SALARY AGE
Employee_Id
101             ANKUR   MALE      10000  32
105            ARCHIT   MALE   12500000  29
106            ANIKET   MALE    2340000  30
108           ATHARVA   MALE   34520000  38
109             VARAD   MALE    1007800  26
111            ATHARY   MALE   78650000  53
112             SAHIL   MALE   56740000  49
113          UTKARSHA   MALE  567410000  53

In [194]:
df[df.GENDER=='MALE'][df.SALARY>10000000]

C:\Users\user5\AppData\Local\Temp\ipykernel_19292\2998209842.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df.GENDER=='MALE'][df.SALARY>10000000]

                 NAME GENDER     SALARY AGE
Employee_Id
105            ARCHIT   MALE   12500000  29
108           ATHARVA   MALE   34520000  38
111            ATHARY   MALE   78650000  53
112             SAHIL   MALE   56740000  49
113          UTKARSHA   MALE  567410000  53

In [195]:
df[df.GENDER=='MALE'][df.SALARY>10000000][df.AGE>32]

C:\Users\user5\AppData\Local\Temp\ipykernel_19292\905812890.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df.GENDER=='MALE'][df.SALARY>10000000][df.AGE>32]
C:\Users\user5\AppData\Local\Temp\ipykernel_19292\905812890.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df.GENDER=='MALE'][df.SALARY>10000000][df.AGE>32]

                 NAME GENDER     SALARY AGE
Employee_Id
108           ATHARVA   MALE   34520000  38
111            ATHARY   MALE   78650000  53
112             SAHIL   MALE   56740000  49
113          UTKARSHA   MALE  567410000  53

In [269]:
df

                   NAME  GENDER     SALARY  AGE
Employee_Id
101               ANKUR    MALE      10000   32
102              SARWAT  FEMALE   12890000   49
103          GEETANJALI  FEMALE   15670000   29
104               DISHA  FEMALE    4500000   47
105              ARCHIT    MALE   12500000   29
106              ANIKET    MALE    2340000   30
107            TEJASHRI  FEMALE   76590000   38
108             ATHARVA    MALE   34520000   38
109             SHUBHAM    MALE    5500000   24
110               NISHA  FEMALE   45630000   27
111              ATHARY    MALE   78650000   53
112               SAHIL    MALE   56740000   49
113            UTKARSHA    MALE  567410000   53
114               MIRAL  FEMALE  456310000   52
115               rakhi  female     555555   24
116                 NaN     NaN     555555  NaN
117             SHUBHAM    MALE   55000000   28

In [275]:
df[df.NAME=='SHUBHAM']

                NAME GENDER    SALARY AGE
Employee_Id
109          SHUBHAM   MALE   5500000  24
117          SHUBHAM   MALE  55000000  28

In [283]:
df

                   NAME  GENDER     SALARY  AGE
Employee_Id
101               ANKUR    MALE      10000   32
102              SARWAT  FEMALE   12890000   49
103          GEETANJALI  FEMALE   15670000   29
104               DISHA  FEMALE    4500000   47
105              ARCHIT    MALE   12500000   29
106              ANIKET    MALE    2340000   30
107            TEJASHRI  FEMALE   76590000   38
108             ATHARVA    MALE   34520000   38
109             SHUBHAM    MALE    5500000   24
110               NISHA  FEMALE   45630000   27
111              ATHARY    MALE   78650000   53
112               SAHIL    MALE   56740000   49
113            UTKARSHA    MALE  567410000   53
114               MIRAL  FEMALE  456310000   52
115               rakhi  female     555555   24
116                 NaN     NaN     555555  NaN

In [284]:
df.drop(116,axis=0,inplace=True)
df

                   NAME  GENDER     SALARY AGE
Employee_Id
101               ANKUR    MALE      10000  32
102              SARWAT  FEMALE   12890000  49
103          GEETANJALI  FEMALE   15670000  29
104               DISHA  FEMALE    4500000  47
105              ARCHIT    MALE   12500000  29
106              ANIKET    MALE    2340000  30
107            TEJASHRI  FEMALE   76590000  38
108             ATHARVA    MALE   34520000  38
109             SHUBHAM    MALE    5500000  24
110               NISHA  FEMALE   45630000  27
111              ATHARY    MALE   78650000  53
112               SAHIL    MALE   56740000  49
113            UTKARSHA    MALE  567410000  53
114               MIRAL  FEMALE  456310000  52
115               rakhi  female     555555  24

In [285]:
df['EDUCATION'] = np.random.randstr(a,z,15)
df

AttributeError: module 'numpy.random' has no attribute 'randstr'

In [286]:
cities = [
    "Mumbai", "Pune", "Delhi", "Bengaluru",
    "Hyderabad", "Chennai", "Kolkata", "Ahmedabad"
]
df["CITY"] = np.random.choice(cities, 15)
df

                   NAME  GENDER     SALARY AGE       CITY
Employee_Id
101               ANKUR    MALE      10000  32     Mumbai
102              SARWAT  FEMALE   12890000  49     Mumbai
103          GEETANJALI  FEMALE   15670000  29  Hyderabad
104               DISHA  FEMALE    4500000  47    Kolkata
105              ARCHIT    MALE   12500000  29  Ahmedabad
106              ANIKET    MALE    2340000  30  Hyderabad
107            TEJASHRI  FEMALE   76590000  38  Ahmedabad
108             ATHARVA    MALE   34520000  38  Ahmedabad
109             SHUBHAM    MALE    5500000  24     Mumbai
110               NISHA  FEMALE   45630000  27  Bengaluru
111              ATHARY    MALE   78650000  53  Hyderabad
112               SAHIL    MALE   56740000  49      Delhi
113            UTKARSHA    MALE  567410000  53  Bengaluru
114               MIRAL  FEMALE  456310000  52     Mumbai
115               rakhi  female     555555  24    Chennai

In [298]:
df.loc[115,'NAME']

'rakhi'

In [335]:
df.loc[df.AGE>40]

                 NAME  GENDER     SALARY AGE       CITY
Employee_Id
102            SARWAT  FEMALE   12890000  49     Mumbai
104             DISHA  FEMALE    4500000  47    Kolkata
111            ATHARY    MALE   78650000  53  Hyderabad
112             SAHIL    MALE   56740000  49      Delhi
113          UTKARSHA    MALE  567410000  53  Bengaluru
114             MIRAL  FEMALE  456310000  52     Mumbai

In [334]:
print(df.dtypes)

NAME      object
GENDER    object
SALARY    object
AGE       object
CITY      object
dtype: object

 ## PRACTICE YT VIDEO

# What is Data Manipulation and Analysis?
# Data Manipulation
Definition: Changing, organizing, or preparing data to make it useful and easier to understand.
Goal: To clean, transform, and structure raw data for better usability.
Example:
Organizing a Grocery List: Sorting random items into categories like "Fruits" or "Dairy".
Fixing Errors in a Student Record: Correcting missing or wrong grades.
# Data Analysis
Definition: Extracting patterns, trends, and insights from the data to solve problems.
Goal: To answer questions or identify trends using the data.
Example:
Analyzing Sales Trends: Finding the month with the highest revenue.
Tracking Fitness Progress: Analyzing daily steps and calories for activity.

In [1]:
import pandas as pd

# READ FILE JSON ,CSV ,EXEL

In [4]:
df=pd.read_excel('SampleSuperstore.xlsx')
df

ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 2.0.1 for xls Excel support Use pip or conda to install xlrd.

In [5]:
import openpyxl
print(openpyxl.__version__)

3.1.5

In [6]:
df= pd.read_json('sample_Data.json')
df

,id,name,description,price,category,image
0,1,Apple iPhone 12,The Apple iPhone 12 features a 6.1-inch Super ...,999.00,Electronics,https://www.apple.com/newsroom/images/product/...
1,2,Samsung Galaxy S21,The Samsung Galaxy S21 features a 6.2-inch Dyn...,799.00,Electronics,https://images.samsung.com/is/image/samsung/p6...
2,3,Sony PlayStation 5,The Sony PlayStation 5 features an AMD Zen 2-b...,499.99,Electronics,https://www.sony.com/image/44baa604124b770c824...
3,4,LG OLED55CXPUA 55-inch 4K OLED TV,The LG OLED55CXPUA 55-inch 4K OLED TV features...,1599.99,Electronics,https://www.lg.com/us/images/tvs/md07501804/ga...
4,5,Bose QuietComfort 35 II Wireless Headphones,The Bose QuietComfort 35 II Wireless Headphone...,299.00,Electronics,https://assets.bose.com/content/dam/Bose_DAM/W...
5,6,Fitbit Versa 3 Smartwatch,The Fitbit Versa 3 Smartwatch features a built...,229.95,Electronics,https://www.fitbit.com/global/content/dam/fitb...
6,7,KitchenAid Stand Mixer,The KitchenAid Stand Mixer features a 5-quart ...,399.99,Home & Kitchen,https://www.kitchenaid.com/content/dam/global/...
7,8,Dyson V11 Absolute Cordless Vacuum,The Dyson V11 Absolute Cordless Vacuum feature...,699.99,Home Appliances,https://www.dysoncanada.ca/dam/dyson/images/pr...
8,9,Ninja Foodi Smart XL Grill,The Ninja Foodi Smart XL Grill features 6-in-1...,279.99,Home & Kitchen,https://www.ninjakitchen.com/medias/Ninja-OP50...
9,10,Canon EOS Rebel T8i DSLR Camera,The Canon EOS Rebel T8i DSLR Camera features a...,899.00,Electronics,https://www.canon.com.au/-/media/images/produc...
10,11,Apple AirPods Pro,The Apple AirPods Pro feature active noise can...,249.00,Electronics,https://www.apple.com/v/airpods-pro/b/images/m...
11,12,Bose QuietComfort 35 II Wireless Headphones,The Bose QuietComfort 35 II Wireless Headphone...,299.00,Electronics,https://assets.bose.com/content/dam/Bose_DAM/W...
12,13,Fitbit Charge 4 Fitness Tracker,The Fitbit Charge 4 Fitness Tracker features G...,129.95,Electronics,https://www.fitbit.com/global/content/dam/fitb...
13,14,Samsung Galaxy Watch3,The Samsung Galaxy Watch3 features a rotating ...,399.99,Electronics,https://images.samsung.com/is/image/samsung/as...
14,15,Sony WH-1000XM4 Wireless Noise-Cancelling Head...,The Sony WH-1000XM4 Wireless Noise-Cancelling ...,349.99,Electronics,https://www.sony.com/image/1cdd6354c4cd21cc4f7...
15,16,Breville Barista Express Espresso Machine,The Breville Barista Express Espresso Machine ...,699.95,Home & Kitchen,https://www.breville.com/content/dam/breville/...
16,17,Keurig K-Elite Coffee Maker,The Keurig K-Elite Coffee Maker features a str...,169.99,Home & Kitchen,https://www.keurig.com/content/dam/global-ecom...
17,18,iRobot Roomba i7+ Robot Vacuum,The iRobot Roomba i7+ Robot Vacuum features au...,799.99,Home & Kitchen,https://store.irobot.com/default/i7-vacuuming-...
18,19,Ninja Foodi Digital Air Fry Oven,The Ninja Foodi Digital Air Fry Oven features ...,209.99,Home & Kitchen,https://www.ninjakitchen.com/static/img/produc...
19,20,Cuisinart ICE-70 Ice Cream Maker,The Cuisinart ICE-70 Ice Cream Maker features ...,139.99,Home & Kitchen,https://www.cuisinart.com/share/images/product...

# HOW TO SAVE THE DATA IN FILE

In [8]:
data = {

    'Name' : ['RAM','SHYAM','GHANSHYA'],
    'AGE'    : [10,20,30],
    'CITY'  : ['NAGPUR','PUNE','MUMBAI']
}
df = pd.DataFrame(data)
df

       Name  AGE    CITY
0       RAM   10  NAGPUR
1     SHYAM   20    PUNE
2  GHANSHYA   30  MUMBAI

In [11]:
 # df.to_csv('output.csv')

In [13]:
df.to_csv('outputt.csv',index=False)

In [14]:
df.to_excel('outputt.xlsx',index=False)

In [15]:
df.to_json('outputt.json',index=False)

# why explore dataset ?
## 1 understand the data set
## 2 identify the problem
## 3  plan next step

# INFO () method

- find how many column and row are in set 
- what type of data tpes for each col
- is there missing value

In [ ]:
df.info()

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   AGE     3 non-null      int64
 2   CITY    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

# DESCRIBE method 
  - used to generate summary statistics of a DataFrame or Series.
  - it work with int ccolumn

In [28]:
import pandas as pd

data = {
    'Name':['shubham','rakhi','Ram','shym','sanket'],
    'Age': [20, 25, 30, 35, 40],
    'Salary': [30000, 40000, 50000, 60000, 70000]
}

df = pd.DataFrame(data)

df.describe()

             Age        Salary
count   5.000000      5.000000
mean   30.000000  50000.000000
std     7.905694  15811.388301
min    20.000000  30000.000000
25%    25.000000  40000.000000
50%    30.000000  50000.000000
75%    35.000000  60000.000000
max    40.000000  70000.000000

# specific column  , filters row  , combine multiple conditions

In [32]:
df['Age']

0    20
1    25
2    30
3    35
4    40
Name: Age, dtype: int64

In [34]:
df[['Name','Age']]

      Name  Age
0  shubham   20
1    rakhi   25
2      Ram   30
3     shym   35
4   sanket   40

In [38]:
df[df.Salary > 50000]

     Name  Age  Salary
3    shym   35   60000
4  sanket   40   70000

In [44]:

# BOTH CONDITION SHUOLD TRUW THEN IT WILL WORK..
df[(df.Salary > 50000) & (df.Age > 30)]

     Name  Age  Salary
3    shym   35   60000
4  sanket   40   70000

In [45]:
# AT LEAST ONE CONDITION IS TRUE THEN IT WILL WORK

     Name  Age  Salary
3    shym   35   60000
4  sanket   40   70000

In [46]:
df

      Name  Age  Salary
0  shubham   20   30000
1    rakhi   25   40000
2      Ram   30   50000
3     shym   35   60000
4   sanket   40   70000

# add new column to data set

In [48]:
df['Bonus']  = df['Salary'] *0.1
df

      Name  Age  Salary   Bonus
0  shubham   20   30000  3000.0
1    rakhi   25   40000  4000.0
2      Ram   30   50000  5000.0
3     shym   35   60000  6000.0
4   sanket   40   70000  7000.0

In [54]:
## 2nd way to add new col  [USE FOR PERTICULAR INDEX TO ADD NEW COL]

df.insert(0,"EMP ID" ,[10,20,30,40,50])
df

ValueError: cannot insert EMP ID, already exists

In [51]:
df.insert(2," ID" ,[101,202,303,404,505])
df

   EMP ID     Name   ID  Age  Salary   Bonus
0      10  shubham  101   20   30000  3000.0
1      20    rakhi  202   25   40000  4000.0
2      30      Ram  303   30   50000  5000.0
3      40     shym  404   35   60000  6000.0
4      50   sanket  505   40   70000  7000.0

# UPDATE THE VALUE  

 -df.loc[row_index,'col name']  = new value

In [59]:
df.loc[0,'ID'] = 1010

In [58]:
df

   EMP ID     Name   ID  Age  Salary   Bonus      ID
0      10  shubham  101   20   30000  3000.0  1010.0
1      20    rakhi  202   25   40000  4000.0     NaN
2      30      Ram  303   30   50000  5000.0     NaN
3      40     shym  404   35   60000  6000.0     NaN
4      50   sanket  505   40   70000  7000.0     NaN

In [60]:
df.loc[0,'Salary'] = 550000 
df

   EMP ID     Name   ID  Age  Salary   Bonus      ID
0      10  shubham  101   20  550000  3000.0  1010.0
1      20    rakhi  202   25   40000  4000.0     NaN
2      30      Ram  303   30   50000  5000.0     NaN
3      40     shym  404   35   60000  6000.0     NaN
4      50   sanket  505   40   70000  7000.0     NaN

In [61]:
df.loc[2,'Bonus'] = 550 
df

   EMP ID     Name   ID  Age  Salary   Bonus      ID
0      10  shubham  101   20  550000  3000.0  1010.0
1      20    rakhi  202   25   40000  4000.0     NaN
2      30      Ram  303   30   50000   550.0     NaN
3      40     shym  404   35   60000  6000.0     NaN
4      50   sanket  505   40   70000  7000.0     NaN

In [64]:
# INCREASING SALARY BY THE 5 % 
df['Salary'] = df['Salary'] *1.05
df

   EMP ID     Name   ID  Age    Salary   Bonus      ID
0      10  shubham  101   20  577500.0  3000.0  1010.0
1      20    rakhi  202   25   42000.0  4000.0     NaN
2      30      Ram  303   30   52500.0   550.0     NaN
3      40     shym  404   35   63000.0  6000.0     NaN
4      50   sanket  505   40   73500.0  7000.0     NaN

# REMOVING COL

In [73]:
df.drop('ID',inplace=True,axis=1 )
df

   EMP ID     Name   ID  Age    Salary   Bonus
0      10  shubham  101   20  577500.0  3000.0
1      20    rakhi  202   25   42000.0  4000.0
2      30      Ram  303   30   52500.0   550.0
3      40     shym  404   35   63000.0  6000.0
4      50   sanket  505   40   73500.0  7000.0

In [71]:
df.columns

Index(['EMP ID', 'Name', ' ID', 'Age', 'Salary', 'Bonus', 'ID'], dtype='object')

In [77]:
df

   EMP ID     Name  Age    Salary   Bonus
0      10  shubham   20  577500.0  3000.0
1      20    rakhi   25   42000.0  4000.0
2      30      Ram   30   52500.0   550.0
3      40     shym   35   63000.0  6000.0
4      50   sanket   40   73500.0  7000.0

In [78]:
# 2nd way 
df.drop(columns=[' ID'],inplace=True)
df

KeyError: "[' ID'] not found in axis"

# FUNCTION

In [83]:
df

           NAME  GENDER     SALARY
101       ANKUR    MALE      10000
102      SARWAT  FEMALE   12890000
103  GEETANJALI  FEMALE   15670000
104       DISHA  FEMALE    4500000
105      ARCHIT    MALE   12500000
106      ANIKET    MALE    2340000
107    TEJASHRI  FEMALE   76590000
108     ATHARVA    MALE   34520000
109       VARAD    MALE    1007800
110       NISHA  FEMALE   45630000
111      ATHARY    MALE   78650000
112       SAHIL    MALE   56740000
113    UTKARSHA    MALE  567410000
114       MIRAL  FEMALE  456310000
115   VAISHNAVI  FEMALE  786540000

In [86]:
df.loc[116] = df.loc[111]
df.loc[117] = df.loc[114]

df.loc[118] = ['Amkush','Male',np.nan] 
df.loc[119] = ['Krishna','Male',np.nan] 

df

           NAME  GENDER       SALARY
101       ANKUR    MALE      10000.0
102      SARWAT  FEMALE   12890000.0
103  GEETANJALI  FEMALE   15670000.0
104       DISHA  FEMALE    4500000.0
105      ARCHIT    MALE   12500000.0
106      ANIKET    MALE    2340000.0
107    TEJASHRI  FEMALE   76590000.0
108     ATHARVA    MALE   34520000.0
109       VARAD    MALE    1007800.0
110       NISHA  FEMALE   45630000.0
111      ATHARY    MALE   78650000.0
112       SAHIL    MALE   56740000.0
113    UTKARSHA    MALE  567410000.0
114       MIRAL  FEMALE  456310000.0
115   VAISHNAVI  FEMALE  786540000.0
116      ATHARY    MALE   78650000.0
117       MIRAL  FEMALE  456310000.0
118      Amkush    Male          NaN
119     Krishna    Male          NaN

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19 entries, 101 to 119
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   NAME    19 non-null     object
 1   GENDER  19 non-null     object
 2   SALARY  17 non-null     float64
dtypes: float64(1), object(2)
memory usage: 608.0+ bytes

In [88]:
df.head()

           NAME  GENDER      SALARY
101       ANKUR    MALE     10000.0
102      SARWAT  FEMALE  12890000.0
103  GEETANJALI  FEMALE  15670000.0
104       DISHA  FEMALE   4500000.0
105      ARCHIT    MALE  12500000.0

In [89]:
df.tail()

          NAME  GENDER       SALARY
115  VAISHNAVI  FEMALE  786540000.0
116     ATHARY    MALE   78650000.0
117      MIRAL  FEMALE  456310000.0
118     Amkush    Male          NaN
119    Krishna    Male          NaN

In [90]:
df.isnull().sum()

NAME      0
GENDER    0
SALARY    2
dtype: int64

In [91]:
df.notnull().sum()

NAME      19
GENDER    19
SALARY    17
dtype: int64

In [92]:
df.duplicated().sum()

np.int64(2)

In [93]:
df.nunique()

NAME      17
GENDER     3
SALARY    15
dtype: int64

In [94]:
df.NAME.unique()

array(['ANKUR', 'SARWAT', 'GEETANJALI', 'DISHA', 'ARCHIT', 'ANIKET',
       'TEJASHRI', 'ATHARVA', 'VARAD', 'NISHA', 'ATHARY', 'SAHIL',
       'UTKARSHA', 'MIRAL', 'VAISHNAVI', 'Amkush', 'Krishna'],
      dtype=object)

In [96]:
df.GENDER.unique()

array(['MALE', 'FEMALE', 'Male'], dtype=object)

In [107]:
df.sort_values(by='NAME' )                # by efault it will sort in the sacedning the formant

           NAME  GENDER       SALARY
106      ANIKET    MALE    2340000.0
101       ANKUR    MALE      10000.0
105      ARCHIT    MALE   12500000.0
108     ATHARVA    MALE   34520000.0
116      ATHARY    MALE   78650000.0
111      ATHARY    MALE   78650000.0
118      Amkush    Male          NaN
104       DISHA  FEMALE    4500000.0
103  GEETANJALI  FEMALE   15670000.0
119     Krishna    Male          NaN
114       MIRAL  FEMALE  456310000.0
117       MIRAL  FEMALE  456310000.0
110       NISHA  FEMALE   45630000.0
112       SAHIL    MALE   56740000.0
102      SARWAT  FEMALE   12890000.0
107    TEJASHRI  FEMALE   76590000.0
113    UTKARSHA    MALE  567410000.0
115   VAISHNAVI  FEMALE  786540000.0
109       VARAD    MALE    1007800.0

In [60]:
df.sort_values(by='GENDER')
df

KeyError: 'GENDER'

In [106]:
df.sort_values(by='NAME' ,ascending =False)

           NAME  GENDER       SALARY
109       VARAD    MALE    1007800.0
115   VAISHNAVI  FEMALE  786540000.0
113    UTKARSHA    MALE  567410000.0
107    TEJASHRI  FEMALE   76590000.0
102      SARWAT  FEMALE   12890000.0
112       SAHIL    MALE   56740000.0
110       NISHA  FEMALE   45630000.0
117       MIRAL  FEMALE  456310000.0
114       MIRAL  FEMALE  456310000.0
119     Krishna    Male          NaN
103  GEETANJALI  FEMALE   15670000.0
104       DISHA  FEMALE    4500000.0
118      Amkush    Male          NaN
111      ATHARY    MALE   78650000.0
116      ATHARY    MALE   78650000.0
108     ATHARVA    MALE   34520000.0
105      ARCHIT    MALE   12500000.0
101       ANKUR    MALE      10000.0
106      ANIKET    MALE    2340000.0

In [108]:
pd.concat([df,df],axis=1)

           NAME  GENDER       SALARY        NAME  GENDER       SALARY
101       ANKUR    MALE      10000.0       ANKUR    MALE      10000.0
102      SARWAT  FEMALE   12890000.0      SARWAT  FEMALE   12890000.0
103  GEETANJALI  FEMALE   15670000.0  GEETANJALI  FEMALE   15670000.0
104       DISHA  FEMALE    4500000.0       DISHA  FEMALE    4500000.0
105      ARCHIT    MALE   12500000.0      ARCHIT    MALE   12500000.0
106      ANIKET    MALE    2340000.0      ANIKET    MALE    2340000.0
107    TEJASHRI  FEMALE   76590000.0    TEJASHRI  FEMALE   76590000.0
108     ATHARVA    MALE   34520000.0     ATHARVA    MALE   34520000.0
109       VARAD    MALE    1007800.0       VARAD    MALE    1007800.0
110       NISHA  FEMALE   45630000.0       NISHA  FEMALE   45630000.0
111      ATHARY    MALE   78650000.0      ATHARY    MALE   78650000.0
112       SAHIL    MALE   56740000.0       SAHIL    MALE   56740000.0
113    UTKARSHA    MALE  567410000.0    UTKARSHA    MALE  567410000.0
114       MIRAL  FEMALE  456310000.0       MIRAL  FEMALE  456310000.0
115   VAISHNAVI  FEMALE  786540000.0   VAISHNAVI  FEMALE  786540000.0
116      ATHARY    MALE   78650000.0      ATHARY    MALE   78650000.0
117       MIRAL  FEMALE  456310000.0       MIRAL  FEMALE  456310000.0
118      Amkush    Male          NaN      Amkush    Male          NaN
119     Krishna    Male          NaN     Krishna    Male          NaN

In [109]:
pd.concat([df,df],axis=0)

           NAME  GENDER       SALARY
101       ANKUR    MALE      10000.0
102      SARWAT  FEMALE   12890000.0
103  GEETANJALI  FEMALE   15670000.0
104       DISHA  FEMALE    4500000.0
105      ARCHIT    MALE   12500000.0
106      ANIKET    MALE    2340000.0
107    TEJASHRI  FEMALE   76590000.0
108     ATHARVA    MALE   34520000.0
109       VARAD    MALE    1007800.0
110       NISHA  FEMALE   45630000.0
111      ATHARY    MALE   78650000.0
112       SAHIL    MALE   56740000.0
113    UTKARSHA    MALE  567410000.0
114       MIRAL  FEMALE  456310000.0
115   VAISHNAVI  FEMALE  786540000.0
116      ATHARY    MALE   78650000.0
117       MIRAL  FEMALE  456310000.0
118      Amkush    Male          NaN
119     Krishna    Male          NaN
101       ANKUR    MALE      10000.0
102      SARWAT  FEMALE   12890000.0
103  GEETANJALI  FEMALE   15670000.0
104       DISHA  FEMALE    4500000.0
105      ARCHIT    MALE   12500000.0
106      ANIKET    MALE    2340000.0
107    TEJASHRI  FEMALE   76590000.0
108     ATHARVA    MALE   34520000.0
109       VARAD    MALE    1007800.0
110       NISHA  FEMALE   45630000.0
111      ATHARY    MALE   78650000.0
112       SAHIL    MALE   56740000.0
113    UTKARSHA    MALE  567410000.0
114       MIRAL  FEMALE  456310000.0
115   VAISHNAVI  FEMALE  786540000.0
116      ATHARY    MALE   78650000.0
117       MIRAL  FEMALE  456310000.0
118      Amkush    Male          NaN
119     Krishna    Male          NaN

In [110]:
df.NAME.value_counts()

NAME
MIRAL         2
ATHARY        2
ANKUR         1
NISHA         1
Amkush        1
VAISHNAVI     1
UTKARSHA      1
SAHIL         1
VARAD         1
SARWAT        1
ATHARVA       1
TEJASHRI      1
ANIKET        1
ARCHIT        1
DISHA         1
GEETANJALI    1
Krishna       1
Name: count, dtype: int64

In [111]:
df.GENDER.value_counts()

GENDER
MALE      9
FEMALE    8
Male      2
Name: count, dtype: int64

In [112]:
df.count()

NAME      19
GENDER    19
SALARY    17
dtype: int64

In [114]:
df.describe()

             SALARY
count  1.700000e+01
mean   1.580158e+08
std    2.446796e+08
min    1.000000e+04
25%    1.250000e+07
50%    4.563000e+07
75%    7.865000e+07
max    7.865400e+08

In [115]:
df.SALARY.mean()

np.float64(158015752.94117647)

In [117]:
df["AGE"] = np.random.randint(1,50,19)

In [118]:
df

           NAME  GENDER       SALARY  AGE
101       ANKUR    MALE      10000.0   19
102      SARWAT  FEMALE   12890000.0   23
103  GEETANJALI  FEMALE   15670000.0   42
104       DISHA  FEMALE    4500000.0   24
105      ARCHIT    MALE   12500000.0    7
106      ANIKET    MALE    2340000.0   28
107    TEJASHRI  FEMALE   76590000.0   28
108     ATHARVA    MALE   34520000.0   45
109       VARAD    MALE    1007800.0    5
110       NISHA  FEMALE   45630000.0   22
111      ATHARY    MALE   78650000.0   12
112       SAHIL    MALE   56740000.0   18
113    UTKARSHA    MALE  567410000.0    7
114       MIRAL  FEMALE  456310000.0   25
115   VAISHNAVI  FEMALE  786540000.0   34
116      ATHARY    MALE   78650000.0   42
117       MIRAL  FEMALE  456310000.0   34
118      Amkush    Male          NaN    8
119     Krishna    Male          NaN   23

In [119]:
df.AGE.mean()

np.float64(23.473684210526315)

In [121]:
df.SALARY.mean()             # if nan value is there  it will not take for mean

np.float64(158015752.94117647)

# GENDER WISE MEAN

In [122]:
df.groupby(by='GENDER')['AGE'].mean()

GENDER
FEMALE    29.000000
MALE      20.333333
Male      15.500000
Name: AGE, dtype: float64

In [123]:
df.groupby(by='GENDER')['SALARY'].mean()

GENDER
FEMALE    2.318050e+08
MALE      9.242531e+07
Male               NaN
Name: SALARY, dtype: float64

In [124]:
cities = [
    "Mumbai", "Pune", "Delhi", "Bengaluru",
    "Hyderabad", "Chennai", "Kolkata", "Ahmedabad"
]
df["CITY"] = np.random.choice(cities, 19)
df

           NAME  GENDER       SALARY  AGE       CITY
101       ANKUR    MALE      10000.0   19  Ahmedabad
102      SARWAT  FEMALE   12890000.0   23    Chennai
103  GEETANJALI  FEMALE   15670000.0   42      Delhi
104       DISHA  FEMALE    4500000.0   24  Bengaluru
105      ARCHIT    MALE   12500000.0    7     Mumbai
106      ANIKET    MALE    2340000.0   28    Kolkata
107    TEJASHRI  FEMALE   76590000.0   28      Delhi
108     ATHARVA    MALE   34520000.0   45    Kolkata
109       VARAD    MALE    1007800.0    5    Chennai
110       NISHA  FEMALE   45630000.0   22       Pune
111      ATHARY    MALE   78650000.0   12      Delhi
112       SAHIL    MALE   56740000.0   18  Ahmedabad
113    UTKARSHA    MALE  567410000.0    7     Mumbai
114       MIRAL  FEMALE  456310000.0   25  Ahmedabad
115   VAISHNAVI  FEMALE  786540000.0   34    Chennai
116      ATHARY    MALE   78650000.0   42       Pune
117       MIRAL  FEMALE  456310000.0   34  Bengaluru
118      Amkush    Male          NaN    8       Pune
119     Krishna    Male          NaN   23    Kolkata

In [125]:
df.groupby(by=['CITY','GENDER'])['SALARY'].mean()

CITY       GENDER
Ahmedabad  FEMALE    456310000.0
           MALE       28375000.0
Bengaluru  FEMALE    230405000.0
Chennai    FEMALE    399715000.0
           MALE        1007800.0
Delhi      FEMALE     46130000.0
           MALE       78650000.0
Kolkata    MALE       18430000.0
           Male              NaN
Mumbai     MALE      289955000.0
Pune       FEMALE     45630000.0
           MALE       78650000.0
           Male              NaN
Name: SALARY, dtype: float64

In [126]:
df.duplicated().sum()

np.int64(0)

In [127]:
df.drop_duplicates(inplace=True)

In [128]:
df.duplicated().sum()

np.int64(0)

In [130]:
df.loc[116] = df.loc[111]
df.loc[117] = df.loc[114]

df

           NAME  GENDER       SALARY  AGE       CITY
101       ANKUR    MALE      10000.0   19  Ahmedabad
102      SARWAT  FEMALE   12890000.0   23    Chennai
103  GEETANJALI  FEMALE   15670000.0   42      Delhi
104       DISHA  FEMALE    4500000.0   24  Bengaluru
105      ARCHIT    MALE   12500000.0    7     Mumbai
106      ANIKET    MALE    2340000.0   28    Kolkata
107    TEJASHRI  FEMALE   76590000.0   28      Delhi
108     ATHARVA    MALE   34520000.0   45    Kolkata
109       VARAD    MALE    1007800.0    5    Chennai
110       NISHA  FEMALE   45630000.0   22       Pune
111      ATHARY    MALE   78650000.0   12      Delhi
112       SAHIL    MALE   56740000.0   18  Ahmedabad
113    UTKARSHA    MALE  567410000.0    7     Mumbai
114       MIRAL  FEMALE  456310000.0   25  Ahmedabad
115   VAISHNAVI  FEMALE  786540000.0   34    Chennai
116      ATHARY    MALE   78650000.0   12      Delhi
117       MIRAL  FEMALE  456310000.0   25  Ahmedabad
118      Amkush    Male          NaN    8       Pune
119     Krishna    Male          NaN   23    Kolkata

In [131]:
df.duplicated().sum()

np.int64(2)

In [132]:
df.drop_duplicates(inplace=True)

In [133]:
df.duplicated().sum()

np.int64(0)

In [134]:
df.SALARY.mean()

np.float64(143420520.0)

In [135]:
df.SALARY.replace(np.nan,df.SALARY.mean())

101        10000.0
102     12890000.0
103     15670000.0
104      4500000.0
105     12500000.0
106      2340000.0
107     76590000.0
108     34520000.0
109      1007800.0
110     45630000.0
111     78650000.0
112     56740000.0
113    567410000.0
114    456310000.0
115    786540000.0
118    143420520.0
119    143420520.0
Name: SALARY, dtype: float64

In [139]:
df.SALARY.replace(np.nan,df.SALARY.mean() , inplace=True)

C:\Users\user5\AppData\Local\Temp\ipykernel_29244\3905800177.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.SALARY.replace(np.nan,df.SALARY.mean() , inplace=True)

In [140]:
df

           NAME  GENDER       SALARY  AGE       CITY
101       ANKUR    MALE      10000.0   19  Ahmedabad
102      SARWAT  FEMALE   12890000.0   23    Chennai
103  GEETANJALI  FEMALE   15670000.0   42      Delhi
104       DISHA  FEMALE    4500000.0   24  Bengaluru
105      ARCHIT    MALE   12500000.0    7     Mumbai
106      ANIKET    MALE    2340000.0   28    Kolkata
107    TEJASHRI  FEMALE   76590000.0   28      Delhi
108     ATHARVA    MALE   34520000.0   45    Kolkata
109       VARAD    MALE    1007800.0    5    Chennai
110       NISHA  FEMALE   45630000.0   22       Pune
111      ATHARY    MALE   78650000.0   12      Delhi
112       SAHIL    MALE   56740000.0   18  Ahmedabad
113    UTKARSHA    MALE  567410000.0    7     Mumbai
114       MIRAL  FEMALE  456310000.0   25  Ahmedabad
115   VAISHNAVI  FEMALE  786540000.0   34    Chennai
118      Amkush    Male  143420520.0    8       Pune
119     Krishna    Male  143420520.0   23    Kolkata

In [5]:
df

           NAME  GENDER     SALARY
101       ANKUR    MALE      10000
102      SARWAT  FEMALE   12890000
103  GEETANJALI  FEMALE   15670000
104       DISHA  FEMALE    4500000
105      ARCHIT    MALE   12500000
106      ANIKET    MALE    2340000
107    TEJASHRI  FEMALE   76590000
108     ATHARVA    MALE   34520000
109       VARAD    MALE    1007800
110       NISHA  FEMALE   45630000
111      ATHARY    MALE   78650000
112       SAHIL    MALE   56740000
113    UTKARSHA    MALE  567410000
114       MIRAL  FEMALE  456310000
115   VAISHNAVI  FEMALE  786540000

In [39]:
a = np.random.randint(20,40,8)
a

array([33, 38, 32, 23, 23, 23, 25, 33], dtype=int32)

In [10]:
df.insert(3,'AGE',a)

In [11]:
df

           NAME  GENDER     SALARY  AGE
101       ANKUR    MALE      10000   34
102      SARWAT  FEMALE   12890000   26
103  GEETANJALI  FEMALE   15670000   36
104       DISHA  FEMALE    4500000   23
105      ARCHIT    MALE   12500000   35
106      ANIKET    MALE    2340000   35
107    TEJASHRI  FEMALE   76590000   24
108     ATHARVA    MALE   34520000   37
109       VARAD    MALE    1007800   35
110       NISHA  FEMALE   45630000   30
111      ATHARY    MALE   78650000   35
112       SAHIL    MALE   56740000   31
113    UTKARSHA    MALE  567410000   35
114       MIRAL  FEMALE  456310000   21
115   VAISHNAVI  FEMALE  786540000   31

In [14]:
df.loc[102,'AGE']  = np.nan
df

           NAME  GENDER     SALARY   AGE
101       ANKUR    MALE      10000  34.0
102      SARWAT  FEMALE   12890000   NaN
103  GEETANJALI  FEMALE   15670000  36.0
104       DISHA  FEMALE    4500000  23.0
105      ARCHIT    MALE   12500000  35.0
106      ANIKET    MALE    2340000  35.0
107    TEJASHRI  FEMALE   76590000  24.0
108     ATHARVA    MALE   34520000  37.0
109       VARAD    MALE    1007800  35.0
110       NISHA  FEMALE   45630000  30.0
111      ATHARY    MALE   78650000  35.0
112       SAHIL    MALE   56740000  31.0
113    UTKARSHA    MALE  567410000  35.0
114       MIRAL  FEMALE  456310000  21.0
115   VAISHNAVI  FEMALE  786540000  31.0

In [17]:
df.loc[[107,112,114,115,106],'AGE']  = np.nan
df

           NAME  GENDER     SALARY   AGE
101       ANKUR    MALE      10000  34.0
102      SARWAT  FEMALE   12890000   NaN
103  GEETANJALI  FEMALE   15670000  36.0
104       DISHA  FEMALE    4500000  23.0
105      ARCHIT    MALE   12500000   NaN
106      ANIKET    MALE    2340000   NaN
107    TEJASHRI  FEMALE   76590000   NaN
108     ATHARVA    MALE   34520000  37.0
109       VARAD    MALE    1007800  35.0
110       NISHA  FEMALE   45630000  30.0
111      ATHARY    MALE   78650000  35.0
112       SAHIL    MALE   56740000   NaN
113    UTKARSHA    MALE  567410000  35.0
114       MIRAL  FEMALE  456310000   NaN
115   VAISHNAVI  FEMALE  786540000   NaN

In [18]:
df.loc[[107,112,114,115,106],'SALARY']  = np.nan
df

           NAME  GENDER       SALARY   AGE
101       ANKUR    MALE      10000.0  34.0
102      SARWAT  FEMALE   12890000.0   NaN
103  GEETANJALI  FEMALE   15670000.0  36.0
104       DISHA  FEMALE    4500000.0  23.0
105      ARCHIT    MALE   12500000.0   NaN
106      ANIKET    MALE          NaN   NaN
107    TEJASHRI  FEMALE          NaN   NaN
108     ATHARVA    MALE   34520000.0  37.0
109       VARAD    MALE    1007800.0  35.0
110       NISHA  FEMALE   45630000.0  30.0
111      ATHARY    MALE   78650000.0  35.0
112       SAHIL    MALE          NaN   NaN
113    UTKARSHA    MALE  567410000.0  35.0
114       MIRAL  FEMALE          NaN   NaN
115   VAISHNAVI  FEMALE          NaN   NaN

In [19]:
df

           NAME  GENDER       SALARY   AGE
101       ANKUR    MALE      10000.0  34.0
102      SARWAT  FEMALE   12890000.0   NaN
103  GEETANJALI  FEMALE   15670000.0  36.0
104       DISHA  FEMALE    4500000.0  23.0
105      ARCHIT    MALE   12500000.0   NaN
106      ANIKET    MALE          NaN   NaN
107    TEJASHRI  FEMALE          NaN   NaN
108     ATHARVA    MALE   34520000.0  37.0
109       VARAD    MALE    1007800.0  35.0
110       NISHA  FEMALE   45630000.0  30.0
111      ATHARY    MALE   78650000.0  35.0
112       SAHIL    MALE          NaN   NaN
113    UTKARSHA    MALE  567410000.0  35.0
114       MIRAL  FEMALE          NaN   NaN
115   VAISHNAVI  FEMALE          NaN   NaN

# HANDINLING NULL AND NAN VALUE

In [20]:
df.isnull()

      NAME  GENDER  SALARY    AGE
101  False   False   False  False
102  False   False   False   True
103  False   False   False  False
104  False   False   False  False
105  False   False   False   True
106  False   False    True   True
107  False   False    True   True
108  False   False   False  False
109  False   False   False  False
110  False   False   False  False
111  False   False   False  False
112  False   False    True   True
113  False   False   False  False
114  False   False    True   True
115  False   False    True   True

In [21]:
df.AGE.isnull()

101    False
102     True
103    False
104    False
105     True
106     True
107     True
108    False
109    False
110    False
111    False
112     True
113    False
114     True
115     True
Name: AGE, dtype: bool

In [25]:
df.loc[[110],'AGE'].isnull()

110    False
Name: AGE, dtype: bool

In [26]:
df.isnull().sum()

NAME      0
GENDER    0
SALARY    5
AGE       7
dtype: int64

In [32]:
df

           NAME  GENDER       SALARY   AGE
101       ANKUR    MALE      10000.0  34.0
103  GEETANJALI  FEMALE   15670000.0  36.0
104       DISHA  FEMALE    4500000.0  23.0
108     ATHARVA    MALE   34520000.0  37.0
109       VARAD    MALE    1007800.0  35.0
110       NISHA  FEMALE   45630000.0  30.0
111      ATHARY    MALE   78650000.0  35.0
113    UTKARSHA    MALE  567410000.0  35.0

In [33]:
df.loc[[101,104,109,113],'AGE'] = np.nan
df

           NAME  GENDER       SALARY   AGE
101       ANKUR    MALE      10000.0   NaN
103  GEETANJALI  FEMALE   15670000.0  36.0
104       DISHA  FEMALE    4500000.0   NaN
108     ATHARVA    MALE   34520000.0  37.0
109       VARAD    MALE    1007800.0   NaN
110       NISHA  FEMALE   45630000.0  30.0
111      ATHARY    MALE   78650000.0  35.0
113    UTKARSHA    MALE  567410000.0   NaN

In [34]:
df.loc[[103],'SALARY'] = np.nan
df

           NAME  GENDER       SALARY   AGE
101       ANKUR    MALE      10000.0   NaN
103  GEETANJALI  FEMALE          NaN  36.0
104       DISHA  FEMALE    4500000.0   NaN
108     ATHARVA    MALE   34520000.0  37.0
109       VARAD    MALE    1007800.0   NaN
110       NISHA  FEMALE   45630000.0  30.0
111      ATHARY    MALE   78650000.0  35.0
113    UTKARSHA    MALE  567410000.0   NaN

# HANDING THAT NULL VALUE

In [41]:
# drop entire col if one value is also nan

df.dropna(axis = 1,inplace = True)
df

           NAME  GENDER  AGE
101       ANKUR    MALE   33
103  GEETANJALI  FEMALE   38
104       DISHA  FEMALE   32
108     ATHARVA    MALE   23
109       VARAD    MALE   23
110       NISHA  FEMALE   23
111      ATHARY    MALE   25
113    UTKARSHA    MALE   33

In [37]:
a

array([34, 26, 36, 23, 35, 35, 24, 37, 35, 30, 35, 31, 35, 21, 31],
      dtype=int32)

In [40]:
df.insert(2,'AGE',a)
df

           NAME  GENDER  AGE
101       ANKUR    MALE   33
103  GEETANJALI  FEMALE   38
104       DISHA  FEMALE   32
108     ATHARVA    MALE   23
109       VARAD    MALE   23
110       NISHA  FEMALE   23
111      ATHARY    MALE   25
113    UTKARSHA    MALE   33

In [42]:
df.loc[[103],'AGE'] = np.nan
df

           NAME  GENDER   AGE
101       ANKUR    MALE  33.0
103  GEETANJALI  FEMALE   NaN
104       DISHA  FEMALE  32.0
108     ATHARVA    MALE  23.0
109       VARAD    MALE  23.0
110       NISHA  FEMALE  23.0
111      ATHARY    MALE  25.0
113    UTKARSHA    MALE  33.0

In [44]:
df.fillna(0,inplace=True)
df

           NAME  GENDER   AGE
101       ANKUR    MALE  33.0
103  GEETANJALI  FEMALE   0.0
104       DISHA  FEMALE  32.0
108     ATHARVA    MALE  23.0
109       VARAD    MALE  23.0
110       NISHA  FEMALE  23.0
111      ATHARY    MALE  25.0
113    UTKARSHA    MALE  33.0

In [46]:
df.loc[[101,104,109,113],'AGE'] = np.nan
df

           NAME  GENDER   AGE
101       ANKUR    MALE   NaN
103  GEETANJALI  FEMALE   0.0
104       DISHA  FEMALE   NaN
108     ATHARVA    MALE  23.0
109       VARAD    MALE   NaN
110       NISHA  FEMALE  23.0
111      ATHARY    MALE  25.0
113    UTKARSHA    MALE   NaN

In [47]:
df['AGE'].fillna(df['AGE'].mean(),inplace=True)
df

C:\Users\user5\AppData\Local\Temp\ipykernel_4976\1944164864.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['AGE'].fillna(df['AGE'].mean(),inplace=True)

           NAME  GENDER    AGE
101       ANKUR    MALE  17.75
103  GEETANJALI  FEMALE   0.00
104       DISHA  FEMALE  17.75
108     ATHARVA    MALE  23.00
109       VARAD    MALE  17.75
110       NISHA  FEMALE  23.00
111      ATHARY    MALE  25.00
113    UTKARSHA    MALE  17.75

# FILLING PERTIUCLA NAN VALUE  

1 interploate method 
  - when to use
    1  timer series data
    2  numeric data with follow same treand
    3 avoid dropping rows



    # linear interploate = straight-line estimation.
# polynomial interploate = curve-based estimation.
# time interploate = interpolation based on timestamps.

In [49]:
df = pd.DataFrame({
    "Date": pd.to_datetime([
        "2025-01-01",
        "2025-01-02",
        "2025-01-03",
        "2025-01-04",
        "2025-01-05",
        "2025-01-06",
        "2025-01-07"
    ]),
    
    # Straight trend
    "Linear": [10, 20, np.nan, 40, 50, np.nan, 70],
    
    # Curved trend (approximately x²)
    "Polynomial": [1, 4, np.nan, 16, 25, np.nan, 49],
    
    # Time series
    "Sales": [100, np.nan, 140, np.nan, 180, 200, np.nan]
})

df

        Date  Linear  Polynomial  Sales
0 2025-01-01    10.0         1.0  100.0
1 2025-01-02    20.0         4.0    NaN
2 2025-01-03     NaN         NaN  140.0
3 2025-01-04    40.0        16.0    NaN
4 2025-01-05    50.0        25.0  180.0
5 2025-01-06     NaN         NaN  200.0
6 2025-01-07    70.0        49.0    NaN

In [50]:
df["Linear"] = df["Linear"].interpolate(method="linear")
df

        Date  Linear  Polynomial  Sales
0 2025-01-01    10.0         1.0  100.0
1 2025-01-02    20.0         4.0    NaN
2 2025-01-03    30.0         NaN  140.0
3 2025-01-04    40.0        16.0    NaN
4 2025-01-05    50.0        25.0  180.0
5 2025-01-06    60.0         NaN  200.0
6 2025-01-07    70.0        49.0    NaN

# What is order?

order tells Pandas what degree of polynomial (curve) to use when estimating missing values.

Order	Polynomial Type	Equation
# 1	Linear	y=ax+b
# 2	Quadratic	y=ax
2
+bx+c
# 3	Cubic	y=ax
3
+bx
2
+cx+d
# 4	4th-degree polynomial	y=ax
4
+bx
3
+cx
2
+dx+e

In [54]:
df["Polynomial"] = df["Polynomial"].interpolate(method="polynomial", order=2)
df

        Date  Linear  Polynomial  Sales
0 2025-01-01    10.0         1.0  100.0
1 2025-01-02    20.0         4.0    NaN
2 2025-01-03    30.0         9.0  140.0
3 2025-01-04    40.0        16.0    NaN
4 2025-01-05    50.0        25.0  180.0
5 2025-01-06    60.0        36.0  200.0
6 2025-01-07    70.0        49.0    NaN

In [58]:
df = df.set_index("Date") # Set Date as the index
df["Sales"] = df["Sales"].interpolate(method="time")
df

KeyError: "None of ['Date'] are in the columns"

In [61]:
df

            Linear  Polynomial  Sales
Date
2025-01-01    10.0         1.0  100.0
2025-01-02    20.0         4.0  120.0
2025-01-03    30.0         9.0  140.0
2025-01-04    40.0        16.0  160.0
2025-01-05    50.0        25.0  180.0
2025-01-06    60.0        36.0  200.0
2025-01-07    70.0        49.0  200.0

# MERGE AND JOIN THE DATA SET

In [65]:
df_customers = pd.DataFrame ({

   'CustomerID' : [1,2,3],
    'Name'    : ['shubham','suresh','kalpesh']

})



df_Orders = pd.DataFrame ({

  'CustomerID'  : [1,2,4],
    'Orderamout' :[250,350,450]

})
df_customers

   CustomerID     Name
0           1  shubham
1           2   suresh
2           3  kalpesh

# inner join

In [67]:
df_merge = pd.merge(df_customers,df_Orders,on='CustomerID',how="inner")
df_merge

   CustomerID     Name  Orderamout
0           1  shubham         250
1           2   suresh         350

# outer join

In [68]:
df_merge = pd.merge(df_customers,df_Orders,on='CustomerID',how="outer")
df_merge

   CustomerID     Name  Orderamout
0           1  shubham       250.0
1           2   suresh       350.0
2           3  kalpesh         NaN
3           4      NaN       450.0

# LEFT JOIN

In [69]:
df_merge = pd.merge(df_customers,df_Orders,on='CustomerID',how="left")
df_merge

   CustomerID     Name  Orderamout
0           1  shubham       250.0
1           2   suresh       350.0
2           3  kalpesh         NaN

# right join

In [70]:
df_merge = pd.merge(df_customers,df_Orders,on='CustomerID',how="right")
df_merge

   CustomerID     Name  Orderamout
0           1  shubham         250
1           2   suresh         350
2           4      NaN         450